### ISSUE TITLE
Can’t make it work

### ISSUE THREAD

**Issue by cedrickp32** [0x-jerry/vscode-remote-snippets#11]
Hi,

i installed your extension as it’s exactly what i need, but i can’t get it to work. I’ve tried with the exemple settings and i don’t see any snippets anywhere. What i am doing wrong ?

**Comment by 0x-jerry** [comment]
First, I'm sorry for that.

But if you provide a minimal reproducible setting and the expected behavior you want, then I can help.

**Comment by cedrickp32** [comment]
Hi,

Thanks for the quick reply. I've used the json file provided in the exemple to test it. If i use the command **insert snippet**, nothing is showing in the list. I'm new to vscode, so maybe something in my setup isn't right. Also, i don't know what the behavior for the update snippets button is, but when i click on it i see 0/1 appear and disapear really quickly. 

Here is my settings json file : 
`{
    "security.workspace.trust.untrustedFiles": "open",
    "JSObfuscator.changeFileExtension": "min.js",
    "git.ignoreMissingGitWarning": true,
    "workbench.colorTheme": "Sublime VSCode Theme",
    "[php]": {},
    "auto-close-tag.SublimeText3Mode": true,
    "workbench.editor.untitled.hint": "hidden",
    "remote-snippets.snippets": [
        {
          "path": "https://raw.githubusercontent.com/hollowtree/vscode-vue-snippets/master/snippets/html.json",
          "language": "vue"
        }
      ]
}`

**Comment by 0x-jerry** [comment]
@cedrickp32 

> Also, i don't know what the behavior for the update snippets button is, but when i click on it i see 0/1 appear and disapear really quickly.

This will re-download remote snippets and store them at `~/.vscode-remote-snippets/config.json`

---

This extension didn't provide command `insert snippet`, so you can't use with that command.

But you can just type some prefix, and the vscode will handle the reset of things.

For example, just type `vt`, and the snippet will show up.

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/14226737/230918918-b045f3ec-124e-4b1c-b5a8-2274f90d8db0.png">

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/14226737/230917614-e4b942c3-1671-4306-9e61-ec6339f71ab0.png">

**Comment by cedrickp32** [comment]
Ok, that's really usefull. I got it working ! Thank you. 

I'm able to get the snippets in vue or javascript files, but i don't see them in html, css or php files. Do you know why ?

**Comment by 0x-jerry** [comment]
This extension only supports these languages for now: `const supportedLang = ['vue', 'typescript', 'javascript', 'markdown']`

I think I need to fix it in the next version.

**Comment by cedrickp32** [comment]
I just tried the new version, and everything is working ! It's really awesome, thank you so much for your help !
